blank_issues_enabled: false
contact_links:
- name: Questions, feature requests, and more ðŸ’¬
  url: https://github.com/bytemare/secp256k1/discussions
  about: Do you need help? Did you make something with secp256k1? Do you have an idea? Tell us about it!